sudo: false
cache: pip
language: python

env:
  global:
    - secure: aPMnYsHgp+QLSh6PbqVL2GbPwldXCPZBXD0El0QadP8zIyKWs985Mt/wcUM0xa4Opf3CQajlgvdJ55WQuxnuep/b6XSuL+F8ETMfYoIqwSfDw25sLuZiAvoP9yASnV3OmhFNwBDF/A2k8XS8Uj4e1jsKYS/zIQtiVY7bXJirwGtkI8xCUkqBCLJgS21dY/Jw6HrMQ06khb5fnYmBFkgKOT21roY92mKlYrjNbcOEGNJYyMi1v4332BhiQ4YYFEqmnPcvuvDtSg44Tkgk/pprf2+QL6al93IrT1QsXPSQFul+3a+W++7VREs09K6G7OUQgM5ASDqefRPthGblMFrBvDWLIEXs3Mh62Euk4/WelR5AC+m1+5VfOLjhw47ym6jBDrLkpxRRVkc0t2dJAUqgB+599wrMqYGW4jraG06AwpYwsk0RnfvBBIXAPEzfQ0VkNPws17XZFRcNITxUZvQfULWbfXTsLvcUYUh0jiCIekCW/ziJ/dsep7r/1SvEA3wF/jmhvZ0vInrfo1iaym7Iaw6QiROa0azmDganmegKiAOHLgievgOz7OSkURSneKuJ9O51Cf5MrKZ5uoANlEvPEnLnf0noR9S9hijIia3RLQ8af3jtV+n9cci8+sEo8sY9+d/UoL1HLgNdJHr+MoShr3Peuj19R48rGDZ9eO5UCZY=
    - secure: rezGEijaTupwWTGMxWZ93T41XzSVj10yFP+wfYIhtvl9HWMgNWKOY5u82kok8705pXscJdCbifYUQjEfGnJ8EPIp9tofffdaS0uPAWjZ0y+n4JFj1+Uw3+UC7pmOiXK81F7f7lF5XkPzI2mjAJH0O1fraKZ/7BJg5bbHtsK0QyJpx1sPVtB8VxWRBO3oFWcTHdtp8+Kxog8OnF7YhOowPRPmFLN5UDv8ZP3kc+s4OaCZjl7zEbv8mVpxsFB+zF6rK68vN6CtrQXhLfeFWY9R0MzgSvsebgmew/YfwYzkqZfALlQ/rXliTdig3npf2S1VXp6lq8eaiaNSDVrTmZbTVz5IOnRLrD3Uw1tPgEnuz1RxYMTM3ROJIpyczIKvhzoTQuatZLKnsgq7zWR0UDnMxmL65mCzFV+4/ty+qguhFQ3VJPiuvmGouSyBs7bgtRbsWILmN/8PsFLDRJl05OGGoWZFtlfHmufOpZFqQxYJCY10hqbW7iuQJNPOf6M/9O80fjinh9JFNyMrY20mP2BMQbC55FYYjRVhndO/0PSPE0xA+3/7isvjEp9zv9kgLyNLDQLG8OJfi78sN0hUH3xG/PJoKTlbp0+xEWDz9jOgY+kQSoZswZ+1pKgzSwVd/nOWMt0nckIxdLNzRCumTiv2FlQpBm4SO7OCAEbRWaanJ1Y=
    - secure: STwXRSVVItfGVozDzlGx+cjNoiTJFhC7mGqaDuSrHOsbKiULziBExGxqx/kH3V7euLP5Wqo/juiGt9R6bBtBE/lzE0uNhICJf/GiaAa/ID5mWw4BzuXcNAtJsi6TvVQU0yTDwscuokT+H/tRv0iY+9p2t7mUPAv0sNg6DPQtxBhPW8uA6Q1hW5honeGpBQKLTXiHFvMKbzJSGE1OP+IshvHzGGFQgr2+Mby5/ZgzcqMKZALwzGnruZJMlNf//6mDG763qEGv/kR0CswPo0w3q+TQ3RMoCRkoUsGgvW2dhWoWTwCK4FD88W+JaLjgq75dIsoaBYEMICoCDKuyn756fgx82wUv+KPvf5fAcj6KikuMAfAuMUB9/5TGF1RMsGI4XkFY7Piz78oqpqnokmKq4g1wX4AcrVrC6U6F2zhuhxW2YySHG3zV2wJA1z7DZDDCijh6dTCZlLGbvUHteQc4arP2/YMTVrWwzkSklgNJZdSAX/4Na02c0W7o2KUQXJc8OKodIBzllJEpAYWRqxjjH7alu7lY+la3lnWy6tapb6w70+2/NJYXyqAhO+/l+/cOeE3zgCXF/EtqbIT0YdxBShuzJvDfNbusKn7ZsvOJXqgc3LZPlGudlG3HlcHTyG/7ab38jNRPg8D/jAPiQzJSXU/kIi0xnG/y7aXhGibyRzY=
    - secure: Ss4SS5u/pRdzp52urXHaFZd3RSnhHYGWrSG9YMiRhVR/SqM+m3XXDSgCGraax4K+gZL/rZe4gt0yF82zO2+V1F6cTBjOB2Jp1sXW1oS33JWDR0cTHBTbkcRIEdBCt+Fgo8QlsKQBPRtX2Csuu/JE6MwYtbodUAO1zRNr88DQC7GL+IV9Zh7kicUOTAFJKE9B1pjDuaPiqkGOxZAXwbaO8fvaYk3wEWmcSePy9j33lvhen+0GGDMTjGNeflmY4TVIVQKbY+96y3EEyDYE25X68rKzdKF+UowOKnDefTNgnrq1N7fvU6nVPofmQyzTbyxikfxq/vQu7oWzdUVkppz6vvp4ekjBDl6pYuOR2y1RJCYp45Y6F/+Dk9tNWWTkknRyQp6i2ll2LuUlRvlcmbSh4++FP2kAJaCeUXH3Gj9J1oHizMgdIAuH+FCbpzw1f/me2z50Xqj7Lwc7IBr/Eqa+qzblDmPFNW0pOYDfoCB+5KOPCKMXJmbX/apovIgLXiuV+bOc7uubLjJF/uBkP4W/pcwStBbSXtW+xLpRs+nubldXOgIByXqfZikaMkmwBoiBwvv9936IUVIOO99YkWy/PHqgwrXV1kJNQ/LBvNE+HR3620I2ZqF4QdMZeMSiJe1I/oaUuiticNvDIf4G7H7tibkGFq7YuveaaDEzAxiQBg8=

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: required

script:
  - cd $TRAVIS_BUILD_DIR
  - |
    if [[ "$TRAVIS_TAG" == "" ]]; then
        sed -i "/version = / s/\",$/.$TRAVIS_BUILD_NUMBER\",/" setup.py
    fi
  - pip install . twine
  - python setup.py sdist

deploy:
  - provider: script
    skip_cleanup: true
    script: $TRAVIS_BUILD_DIR/ci/travis/deploy.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: $TRAVIS_BUILD_DIR/ci/travis/deploy.sh
    on:
      tags: true
